### ISSUE TITLE
606b3 table renders incorrectly around page break

### ISSUE THREAD

**Issue by bsandlin** [sec-gov/oh#8] opened 2021-02-01 17:54 UTC
Hi,
  On the 606b3 report, when a table is split by a page break the first row on the new page renders with the numeric values on the 1st page and the border lines and Venue name on the 2nd page.

I attached an example. Please look at the December Order Routing Venues table, the row for "ACMG".

Thank you

[606b3_table_render.zip](https://github.com/sec-gov/oh/files/5905681/606b3_table_render.zip)

**Comment by sec-gov** [comment] 2021-02-01 18:11
I spent a fair bit of time on that, it’s hairy, and thought it was working -- but I will look again.  Thank you very much for the sample for me to look at!

**Comment by awiener1** [comment] 2021-02-04 22:14
Some further insight:

If you look at these two attached examples (data is a modified version of one of the sample files), notice that the table in the first pdf is correctly split between two pages, but the table in the second pdf has the identified issue.

[606b3_overflow.zip](https://github.com/sec-gov/oh/files/5928804/606b3_overflow.zip)

It would appear, based on these two examples. that the table cells and the text within them are handled separately from each other. When a row of cells in the table is larger than the page margins will allow, the row is put on the next page. When the text inside that row is larger than the page margins will allow, the text is put on the next page. However, if the text in the row is able to fit within the page margins while the row of cells itself is too big, then the row is put on the next page but the text remains on the first page.

**Comment by sec-gov** [comment] 2021-02-08 23:46
Thank you.  If you are able to tweak the input file content with more blank cells, no blank cells, extra blank rows, etc., to force the table onto the next page you may wish to consider them, ugly as they may be.  I am continuing to work on the fix.

**Comment by sec-gov** [comment] 2021-02-14 14:26
FIxed in [https://github.com/sec-gov/oh/commit/82f5d20bdb70e5e6c1ce400208567030a64fb851](url), please try it.

**Comment by bcalev** [comment] 2021-02-16 15:43
Good Morning,

We seem to be experiencing the same issue despite the fix.  Has anyone else reported that this has been fixed?  If you require an example please let us know as we will need to anonymize the XML.

Thank you.

**Comment by sec-gov** [comment] 2021-02-16 16:05
Yes, please provide a sample.

**Comment by bcalev** [comment] 2021-02-16 16:47
We will work on providing a sample.  The issue is, when we start changing venues for the purpose of anonymizing the data, the problem is alleviated due to spacing changes.  Will advise.

**Comment by sec-gov** [comment] 2021-02-16 16:55
The underlying problem did appear as a result of long venue names that split across several rows, but I thought I had it fixed.  There are new cases in the samples where you can see a case in which the table break occurs right after the header row, if you want to experiment with one of those.

Also if you open up the console in your browser, look for warning messages there (not INFO, which ar okay) – if there are no WARN messages but the output looks bad, that would be a new problem of some kind.

Thanks.

**Comment by bcalev** [comment] 2021-02-16 17:25
We will conduct some more experiments and attempt to get you an anonymized sample showing the issue.  I currently do not see any WARN messages as an FYI.

**Comment by sec-gov** [comment] 2021-03-04 21:55
Perhaps you could simply anonymize the numbers and leave the venue names (which is probably where the problem lies) as they are.

**Comment by pvellore-psc** [comment] 2021-03-08 20:36
This appears to be easy to reproduce. In the shipped sample file, "606b3_two_table_breaks.xml", each ACME SRV venue takes two rows. Please change the first venue in the first page to span into third row (by changing the venue to, say, "ACME breaks nextpage"), and the defect should show up. Trying different lengths for venue string to make the issue appear/disappear.
Thanks for your attention to resolve this issue.

**Comment by sec-gov** [comment] 2021-03-08 21:34
I will.  Thank you.

**Comment by sec-gov** [comment] 2021-03-14 21:23
Fixed in https://github.com/sec-gov/oh/commit/9758ec72ac70d62b14c47c96584358e96645304d

**Closed as completed by sec-gov** 2021-03-14 21:23 UTC
